name: Hello World Workflow

on:
  schedule:
  - cron: "*/5 * * * *"
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: run greet
      uses: ./.github/actions/greetings
      with: 
        who-to-greet: 'People'