name: Protected envs and stages

on:
  push:
    branches:
      - master
      
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout github repository
        uses: actions/checkout@v4

      - name: Build or simulate building
        run: sleep 5

      - name: Finish building
        run: echo "Build completed successfully"

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-push]
    strategy:
      max-parallel: one
      fail-fast: true
      matrix:
        environment: ['dev','acc']
    environment: ${{ matrix.environment}}
    steps:
      - name: Checkout github repository
        uses: actions/checkout@v4

      - name: Build or simulate building
        run: sleep 5

      - name: Finish building
        run: echo "Build completed successfully"
